import { assert, describe, expect, it } from "vitest";
import { getSpaceIcon } from "../lib/utils/getSpaceIcon";
import { Window } from "../lib/types";

const windows = [
  {
    id: 436,
    pid: 5150,
    app: "kitty",
    title: "",
    frame: {
      x: 813.0,
      y: 814.0,
      w: 1745.0,
      h: 584.0,
    },
    role: "AXWindow",
    subrole: "AXStandardWindow",
    display: 1,
    space: 1,
    level: 0,
    opacity: 1.0,
    "split-type": "horizontal",
    "split-child": "second_child",
    "stack-index": 0,
    "can-move": true,
    "can-resize": true,
    "has-focus": true,
    "has-shadow": false,
    "has-border": true,
    "has-parent-zoom": false,
    "has-fullscreen-zoom": false,
    "is-native-fullscreen": false,
    "is-visible": true,
    "is-minimized": false,
    "is-hidden": false,
    "is-floating": false,
    "is-sticky": false,
    "is-topmost": false,
    "is-grabbed": false,
  },
  {
    id: 1360,
    pid: 14011,
    app: "Code",
    title: "",
    frame: {
      x: 813.0,
      y: 26.0,
      w: 1745.0,
      h: 784.0,
    },
    role: "AXWindow",
    subrole: "AXStandardWindow",
    display: 1,
    space: 1,
    level: 0,
    opacity: 1.0,
    "split-type": "horizontal",
    "split-child": "first_child",
    "stack-index": 0,
    "can-move": true,
    "can-resize": true,
    "has-focus": false,
    "has-shadow": false,
    "has-border": true,
    "has-parent-zoom": false,
    "has-fullscreen-zoom": false,
    "is-native-fullscreen": false,
    "is-visible": true,
    "is-minimized": false,
    "is-hidden": false,
    "is-floating": false,
    "is-sticky": false,
    "is-topmost": false,
    "is-grabbed": false,
  },
  {
    id: 232,
    pid: 1948,
    app: "Brave Browser",
    title: "",
    frame: {
      x: -1438.0,
      y: 161.0,
      w: 1436.0,
      h: 832.0,
    },
    role: "AXWindow",
    subrole: "AXStandardWindow",
    display: 2,
    space: 3,
    level: 0,
    opacity: 1.0,
    "split-type": "none",
    "split-child": "second_child",
    "stack-index": 0,
    "can-move": true,
    "can-resize": true,
    "has-focus": false,
    "has-shadow": false,
    "has-border": true,
    "has-parent-zoom": false,
    "has-fullscreen-zoom": false,
    "is-native-fullscreen": false,
    "is-visible": true,
    "is-minimized": false,
    "is-hidden": false,
    "is-floating": false,
    "is-sticky": false,
    "is-topmost": false,
    "is-grabbed": false,
  },
  {
    id: 2044,
    pid: 17476,
    app: "Übersicht",
    title: "",
    frame: {
      x: 2.0,
      y: 26.0,
      w: 807.0,
      h: 1372.0,
    },
    role: "AXWindow",
    subrole: "AXStandardWindow",
    display: 1,
    space: 1,
    level: 0,
    opacity: 1.0,
    "split-type": "vertical",
    "split-child": "first_child",
    "stack-index": 0,
    "can-move": true,
    "can-resize": true,
    "has-focus": false,
    "has-shadow": false,
    "has-border": true,
    "has-parent-zoom": false,
    "has-fullscreen-zoom": false,
    "is-native-fullscreen": false,
    "is-visible": true,
    "is-minimized": false,
    "is-hidden": false,
    "is-floating": false,
    "is-sticky": false,
    "is-topmost": false,
    "is-grabbed": false,
  },
  {
    id: 1793,
    pid: 1948,
    app: "Brave Browser",
    title: "",
    frame: {
      x: 2.0,
      y: 26.0,
      w: 2556.0,
      h: 1372.0,
    },
    role: "AXWindow",
    subrole: "AXStandardWindow",
    display: 1,
    space: 2,
    level: 0,
    opacity: 1.0,
    "split-type": "none",
    "split-child": "second_child",
    "stack-index": 0,
    "can-move": true,
    "can-resize": true,
    "has-focus": false,
    "has-shadow": false,
    "has-border": true,
    "has-parent-zoom": false,
    "has-fullscreen-zoom": false,
    "is-native-fullscreen": false,
    "is-visible": false,
    "is-minimized": false,
    "is-hidden": false,
    "is-floating": false,
    "is-sticky": false,
    "is-topmost": false,
    "is-grabbed": false,
  },
  {
    id: 105,
    pid: 701,
    app: "Spotify",
    title: "Spotify Premium",
    frame: {
      x: -1440.0,
      y: 160.0,
      w: 1440.0,
      h: 875.0,
    },
    role: "AXWindow",
    subrole: "AXDialog",
    display: 2,
    space: 4,
    level: 0,
    opacity: 1.0,
    "split-type": "none",
    "split-child": "none",
    "stack-index": 0,
    "can-move": true,
    "can-resize": true,
    "has-focus": false,
    "has-shadow": false,
    "has-border": true,
    "has-parent-zoom": false,
    "has-fullscreen-zoom": false,
    "is-native-fullscreen": false,
    "is-visible": false,
    "is-minimized": true,
    "is-hidden": false,
    "is-floating": true,
    "is-sticky": true,
    "is-topmost": false,
    "is-grabbed": false,
  },
];

describe("getting the correct icon for a space", function () {
  it("Should return the correct icon for a space with a amount of windows", () => {
    expect(getSpaceIcon(windows as Window[])).toEqual("􀅫");
    // In this case it should return the vscode icon as that has the highest priority
  });
});
